main: com.lostmc.pvp.PvP
name: pvp
version: 1.0-SNAPSHOT
authors: [skyprogrammer]
description: PvP bukkit plugin based on core-*, core-bukkit and game-engine
website: loja.lostmc.com.br
load: STARTUP
depend: [ViaVersion, ViaRewind, ProtocolLib]